blog_app/urls.py
from django.urls import path
from .views import post_detail, post_share, post_comment, post_list, post_search
from .feeds import LatestPostFeed

app_name = 'blog_app'


urlpatterns = [
#     path("", PostListView.as_view(), name="post_list"),
    path('', post_list, name = 'post_list'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>", 
         post_detail, name="post_detail"),
    path('<int:post_id>/share/',
         post_share, name="post_share"),
    path('<int:post_id>/comment/', 
         post_comment, name ='post_comment'),
    path('tags/<slug:tag_slug>', post_list, name = 'post_list_by_tag'),
    path('feed/', LatestPostFeed(), name = 'post_feed'),
    path('search/', post_search, name = 'search')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog_app.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog_app.urls", namespace="blog_app")),
     path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
          name='django.contrib.sitemaps.views.sitemap'),
]
# /home/user/Desktop/Trenches/django_project/ml-apprentice/blog_app/urls.py

blog_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# class Author(models.Manager):
#     name = models.CharField(max_length=100)
#     bio = models.CharField(max_length=300)
        
#     def __str__(self):
#         return self.name
    
    
# Create your model
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = BlogPost.Status.PUBLISHED)

class BlogPost(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
        
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 250,
                            unique_for_date = 'publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name = "blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices = Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog_app:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
        
class Comment(models.Model):
    post = models.ForeignKey(BlogPost,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default=True)
    
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog_app/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)
    
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        
        
class SearchForm(forms.Form):
    query = forms.CharField()
    
    

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Comment
from django.http import Http404
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.

# class PostListView(ListView):
#     """
#     Alternative post list view

#     Args:
#         ListView (ListView): _description_
#     """
#     queryset = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = 'blog_app/post/post_list.html'

def post_list(request, tag_slug=None):
    post_list = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__name__in=[tag.name])
    paginator = Paginator(post_list, 3)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.get_page(1)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    return render(request, 
                  'blog_app/post/post_list.html', 
                  {'posts':posts, 'tag':tag})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(BlogPost, 
                             status=BlogPost.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    comments = post.comments.filter(active=True)
    
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).filter(tags__in=post_tags_ids)\
                                            .exclude(id=post.id)    
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags', '-publish')[:4]
                                
    return render(request, 
                  'blog_app/post/post_detail.html', 
                  {'post':post,
                   'comments':comments,
                   'form':form,
                   'similar_posts':similar_posts})
    

def post_share(request, post_id):
    post = get_object_or_404(BlogPost,
                             id=post_id, 
                             status=BlogPost.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            
            send_mail(subject, message, 'yusuphmustaphaladi@gmail.com',
                      [cd['to']])
            sent = True            
    else:
        form = EmailPostForm()
        
    return render(request, 'blog_app/post/share.html', {'post':post,
                                                              'form':form,
                                                              'sent':sent})
    
    
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(BlogPost,
                             id=post_id,
                             status=BlogPost.Status.PUBLISHED)
    comment = None
    
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        
        comment.post = post
        comment.save()
        
    return render(request, 'blog_app/post/comment.html',
                  {'post':post,
                   'form':form,
                   'comment': comment})
    
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', weight='A') +\
            #                 SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).annotate(
            #     search=search_vector,
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(rank__gte=0.3).order_by('-rank')
            results = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog_app/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog_app/templates/blog_app/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>the-ml-apprentice</title>

    <!-- Bootstrap CSS link (assuming you're using Bootstrap) -->
    <link rel="stylesheet" type='text/css' href="https://bootswatch.com/5/flatly/bootstrap.min.css">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog_app:post_list' %}"><img src="{% static 'blog_app/logo.png' %}" alt="Logo" height="30" class="d-inline-block align-text-top" /></a>

        <!-- Search Form -->
        <!-- base.html -->
        <form class="d-flex" role="search" method="get" action="{% url 'blog_app:search' %}">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" />
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <!-- End Search Form -->
      </div>
    </nav>
    <!-- End Navbar -->

    <!-- Bootstrap JS and Popper.js scripts (assuming you're using Bootstrap) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>
  <body>
    <div id="content">
      {% block content %}

      {% endblock %}
    </div>
    <div id="sidebar">
      {% comment %} <p>
        The Machine Learning Apprentice We've written {% total_posts %} blog posts so far.
      </p> {% endcomment %}
      <p>
        <a href="{% url 'blog_app:post_feed' %}">Subscribe to my RSS FEED</a>
      </p>
      <h3>Latest Posts</h3>
      {% show_latest_posts 3 %}
      <h3>Most Commented posts</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul>
        {% for post in most_commented_posts %}
          <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </body>
  <!-- Footer -->
  <footer class="bg-light text-dark py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h5>Contact Us</h5>
          <p>Email: info@mlapprentice.com</p>
        </div>
        <div class="col-md-6">
          <h5>Follow Us</h5>
          <ul class="list-inline">
            <li class="list-inline-item">
              <a href="#" class="text-dark">Facebook</a>
            </li>
            <li class="list-inline-item">
              <a href="#" class="text-dark">Twitter</a>
            </li>
            <li class="list-inline-item">
              <a href="#" class="text-dark">LinkedIn</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- End Footer -->
</html>