blog_app/urls.py
from django.urls import path
from .views import post_detail, post_share, post_comment, post_list, post_search
from .feeds import LatestPostFeed

app_name = 'blog_app'


urlpatterns = [
#     path("", PostListView.as_view(), name="post_list"),
    path('', post_list, name = 'post_list'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>", 
         post_detail, name="post_detail"),
    path('<int:post_id>/share/',
         post_share, name="post_share"),
    path('<int:post_id>/comment/', 
         post_comment, name ='post_comment'),
    path('tags/<slug:tag_slug>', post_list, name = 'post_list_by_tag'),
    path('feed/', LatestPostFeed(), name = 'post_feed'),
    path('search/', post_search, name = 'search')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog_app.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog_app.urls", namespace="blog_app")),
     path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
          name='django.contrib.sitemaps.views.sitemap'),
]
# /home/user/Desktop/Trenches/django_project/ml-apprentice/blog_app/urls.py

blog_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# class Author(models.Manager):
#     name = models.CharField(max_length=100)
#     bio = models.CharField(max_length=300)
        
#     def __str__(self):
#         return self.name
    
    
# Create your model
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = BlogPost.Status.PUBLISHED)

class BlogPost(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
        
    title = models.CharField(max_length = 250)
    slug = models.SlugField(max_length = 250,
                            unique_for_date = 'publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name = "blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices = Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog_app:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
        
class Comment(models.Model):
    post = models.ForeignKey(BlogPost,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default=True)
    
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog_app/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)
    
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        
        
class SearchForm(forms.Form):
    query = forms.CharField()
    
    

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Comment
from django.http import Http404
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.

# class PostListView(ListView):
#     """
#     Alternative post list view

#     Args:
#         ListView (ListView): _description_
#     """
#     queryset = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = 'blog_app/post/post_list.html'

def post_list(request, tag_slug=None):
    post_list = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__name__in=[tag.name])
    paginator = Paginator(post_list, 3)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.get_page(1)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    return render(request, 
                  'blog_app/post/post_list.html', 
                  {'posts':posts, 'tag':tag})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(BlogPost, 
                             status=BlogPost.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    comments = post.comments.filter(active=True)
    
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).filter(tags__in=post_tags_ids)\
                                            .exclude(id=post.id)    
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags', '-publish')[:4]
                                
    return render(request, 
                  'blog_app/post/post_detail.html', 
                  {'post':post,
                   'comments':comments,
                   'form':form,
                   'similar_posts':similar_posts})
    

def post_share(request, post_id):
    post = get_object_or_404(BlogPost,
                             id=post_id, 
                             status=BlogPost.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            
            send_mail(subject, message, 'yusuphmustaphaladi@gmail.com',
                      [cd['to']])
            sent = True            
    else:
        form = EmailPostForm()
        
    return render(request, 'blog_app/post/share.html', {'post':post,
                                                              'form':form,
                                                              'sent':sent})
    
    
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(BlogPost,
                             id=post_id,
                             status=BlogPost.Status.PUBLISHED)
    comment = None
    
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        
        comment.post = post
        comment.save()
        
    return render(request, 'blog_app/post/comment.html',
                  {'post':post,
                   'form':form,
                   'comment': comment})
    
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', weight='A') +\
            #                 SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).annotate(
            #     search=search_vector,
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(rank__gte=0.3).order_by('-rank')
            results = BlogPost.objects.filter(status=BlogPost.Status.PUBLISHED).annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog_app/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog_app/templates/blog_app/post/comment.html
{% extends "blog_app/base.html" %}

{% block content %}
    <h2> Add a Comment </h2>
    {% if comment %}
        <h2>Your Comment has been added.</h2>
        <p>
            <a href="{{post.get_absolute_url}}">Back to the Post</a>
        </p>
    {% else %}
        {% include "blog_app/post/includes/comment_form.html" %}
    {% endif %}   

{% endblock content %}

blog_app/templates/blog_app/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
  <li>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
  </li>
  {% endfor %}
</ul>

blog_app/templates/blog_app/post/pagination.html
<nav aria-label="...">
  <ul class="pagination">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %} {% for p in page.paginator.page_range %}
      <li class="page-item {% if p == page.number %}{% endif %}">
        <a class="page-link" href="?page={{ p }}">{{ p }}</a>
      </li>
    {% endfor %} {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

blog_app/templates/blog_app/post/post_detail.html
{% extends 'blog_app/base.html' %}
{% load blog_tags %}
{% block content %}
  <div class="container mt-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">{{ post.title }}</h1>
        <p class="card-subtitle text-muted">Published {{ post.publish|date:'F d, Y' }} by {{ post.author }}</p>
        <hr />

        <div class="card-text">{{ post.body|markdown }}</div>
      </div>
    </div>

    <div class="mt-3">
      <a class="btn btn-primary" href="{% url 'blog_app:post_share' post.id %}">Share this post</a>
    </div>

    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
      <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
      {% empty %}There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
      <h2 class="mt-4">{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
      <div class="card mt-3">
        <div class="card-body">
          <p class="card-text text-muted">Comment {{ forloop.counter }} by {{ comment.name }} on {{ comment.created|date:'F d, Y' }}</p>
          <div class="card-text">{{ comment.body|linebreaks }}</div>
        </div>
      </div>
      {% empty %}
      <div class="mt-3">
        <p class="text-muted">There are no comments.</p>
      </div>
    {% endfor %}

    <div class="mt-4">
      {% include 'blog_app/post/includes/comment_form.html' %}
    </div>
  </div>
{% endblock %}

blog_app/templates/blog_app/post/post_list.html
{% extends "blog_app/base.html" %}
{% load blog_tags %}
{%block content %}
<div class="post container">
    {% comment %} <h1>Ml Apprentice</h1> {% endcomment %}
    {% if tag %}
        <h2>Posts tagged with "{{tag.name}}"</h2>
    {% endif %}
    {% for post  in posts %}
        <h2>
            <a href="{{post.get_absolute_url}}">
            {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags: 
            {% for tag in post.tags.all %}
            {% comment %} <a href="{% url "blog_app:post_list_by_tag" %}"> {% endcomment %}
            <a href="{% url 'blog_app:post_list_by_tag' tag_slug=tag.slug %}">
                {{tag.name}}
            </a>
            {% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
    {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "blog_app/post/pagination.html"  with page=posts%}
</div>
{% endblock content %}
```

blog_app/templates/blog_app/post/search.html
{% extends 'blog_app/base.html' %}
{% load blog_tags %}

{% block content %}
  {% if query %}
    <h1>Post Containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_result %}
        Found {{ total_result }} result {{ total_result|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:12 }}
      {% empty %}
      <p>There are no results for your query</p>
    {% endfor %}
    <p>
      <a href="{% url 'blog_app:search' %}">Search again</a>
    </p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search" />
    </form>
  {% endif %}
{% endblock %}

blog_app/templates/blog_app/post/share.html
{% extends "blog_app/base.html" %}

{% block content %}
<div class="container mt-4">
    
    {% if sent %}
        <div class="alert alert-success" role="alert">
            <h3>Email sent successfully</h3>
            <p>"{{post.title}}" was successfully sent to {{ form.cleaned_data.to }}.</p>
        </div>
    {% else %}
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Share "{{post.title}}" by email</h3>
                
                <form method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Send Email</button>
                </form>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}